Albist_design/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('index.urls', 'index'), namespace='index')),
    path('services/', include(('services.urls', 'services'), namespace='services')),
    path('portfolio/', include(('portfolio.urls', 'portfolio'), namespace='portfolio')),
    path('pages/', include(('pages.urls', 'pages'), namespace='pages')),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from blog.views import blog

urlpatterns = [
    path('', blog, name='blog')
]

index/urls.py
from django.urls import path
from index.views import home, about

urlpatterns = [
    path('', home, name='home'),
    path('about/', about, name='about')
]

pages/urls.py
from django.urls import path
from pages.views import pages

urlpatterns = [
    path('', pages, name='pages')
]

portfolio/urls.py
from django.urls import path
from portfolio.views import portfolio

urlpatterns = [
    path('', portfolio, name='portfolio')
]

services/urls.py
from django.urls import path
from services.views import services

urlpatterns = [
    path('', services, name='services'),
]

blog/models.py
from django.db import models

# Create your models here.
class MainBlog(models.Model):
	blog_image = models.ImageField(upload_to='main-blog', null=True)
	blog_title = models.CharField(max_length=100, null=True)
	blog_details = models.TextField(max_length=300, null=True)

index/models.py
from django.db import models

# Create your models here.
class TopSlider(models.Model):
	slider_img = models.ImageField(upload_to='topslider', null=True, default='default.jpg')

class OurServices(models.Model):
	service_title = models.CharField(max_length=50, null=True)
	service_detail = models.TextField(max_length=300, null=True)

class ImageGallery(models.Model):
	gallery = models.ImageField(upload_to='imagegallery', null=True)

class EmployeGallery(models.Model):
	emp_name = models.CharField(max_length=100, null=True)
	emp_position = models.CharField(max_length=150, null=True)
	emp_photo = models.ImageField(upload_to='mengallery', null=True)

class FeatersColumn(models.Model):
	feater_title = models.CharField(max_length=50, null=True)
	feater_dep1 = models.CharField(max_length=100, null=True)
	feater_dep2 = models.CharField(max_length=100, null=True)
	feater_dep3 = models.CharField(max_length=100, null=True)
	feater_dep4 = models.CharField(max_length=100, null=True)

pages/models.py
from django.db import models

# Create your models here.

portfolio/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
	blog_img = models.ImageField(upload_to='blog', null=True)
	blog_title = models.CharField(max_length=50, null=True)
	blog_details = models.TextField(max_length=300, null=True)

services/models.py
from django.db import models

# Create your models here.
class BestServices(models.Model):
	best_service_title = models.CharField(max_length=20, null=True)
	best_service_details = models.TextField(max_length=200, null=True)

	def __str__(self):
		return self.best_service_title


class PlanFeaturs(models.Model):
	feature = models.TextField(null=True)

	def __str__(self):
		return self.feature

class UnlimitedPlan(models.Model):
	plan_name = models.CharField(max_length=50, null=True)
	plan_pay = models.IntegerField(null=True)
	plan_feature = models.ManyToManyField(PlanFeaturs)

	def __str__(self):
		return self.plan_name


class PremiumPlan(models.Model):
	plan_name = models.CharField(max_length=50, null=True)
	plan_pay = models.IntegerField(null=True)
	plan_feature = models.ManyToManyField(PlanFeaturs)

	def __str__(self):
		return self.plan_name


class AdvancePlan(models.Model):
	plan_name = models.CharField(max_length=50, null=True)
	plan_pay = models.IntegerField(null=True)
	plan_feature = models.ManyToManyField(PlanFeaturs)

	def __str__(self):
		return self.plan_name

class BasicPlan(models.Model):
	plan_name = models.CharField(max_length=50, null=True)
	plan_pay = models.IntegerField(null=True)
	plan_feature = models.ManyToManyField(PlanFeaturs)

	def __str__(self):
		return self.plan_name


		

blog/views.py
from django.shortcuts import render
from blog.models import MainBlog

# Create your views here.
def blog(request):
	mblog = MainBlog.objects.all()

	context = {
		'mblog': mblog
	}

	return render(request, 'blog/blog.html', context)

index/views.py
from django.shortcuts import render
from index.models import TopSlider, OurServices, ImageGallery, EmployeGallery, FeatersColumn

# Create your views here.
def home(request):
	slider = TopSlider.objects.all()
	services = OurServices.objects.all()
	gallery = ImageGallery.objects.all()
	employe = EmployeGallery.objects.all()
	feater = FeatersColumn.objects.all()

	context = {
		'slider': slider,
		'services': services,
		'gallery': gallery,
		'employe': employe,
		'feater': feater,

	}

	return render(request, 'index/home.html', context)


def about(request):
	return render(request, 'index/about.html')

pages/views.py
from django.shortcuts import render
from index.models import OurServices
from services.models import BestServices

# Create your views here.
def pages(request):
	best_service = BestServices.objects.all()
	# services = OurServices.objects.all()
	# plans = PlanDetails.objects.all()
	# featurs = PlanFeaturs.objects.all()

	context = {
		'best_service': best_service,
		# 'services': services,
		# 'plans': plans,
		# 'featurs': featurs,
	}


	return render(request, 'pages/pages.html', context)

portfolio/views.py
from django.shortcuts import render
from portfolio.models import Blog

# Create your views here.
def portfolio(request):

	blog = Blog.objects.all()

	context = {
		'blog': blog
	}

	return render(request, 'portfolio/portfolio.html', context)

services/views.py
from django.shortcuts import render
from index.models import FeatersColumn
from services.models import BestServices, UnlimitedPlan, PremiumPlan, AdvancePlan, BasicPlan

# Create your views here.
def services(request):
	best_service = BestServices.objects.all()
	unlimited_plan = UnlimitedPlan.objects.all()
	premium_plan = PremiumPlan.objects.all()
	advance_plan = AdvancePlan.objects.all()
	basic_plan = BasicPlan.objects.all()

	context = {
		'best_service': best_service,
		'unlimited_plan': unlimited_plan,
		'premium_plan': premium_plan,
		'advance_plan': advance_plan,
		'basic_plan': basic_plan
	}
	return render(request, 'services/services.html', context)

blog/templates/blog/blog.html
{% extends 'index/base.html' %}

{% block content %}
	
       <section id="about-section">
          <div id="about-text-box">
            <p id='about-page-title'>Blog</p>
       	    <span id='home-page-link'><a href="#">Home</a></span><span>/</span><span id='about-page-link'><a>Blog</a></spna>
       	  </div>  
       </section><!--       /About    -->

              <section>
         <div class="container">
            <div class="row">
               <div class="col-sm-12">
               	{% for object in mblog %}
                  <div class="col-sm-9">
                     <div id="blog-post-box">
                         <img src="{{ object.blog_image.url }}" class="img-responsive" id="blog-main-img">
                         <div id="who-post-blog">
                            <span id="post-date"><i class="far fa-calendar-alt"></i>Agu29, 2018</span>
                            <span id="post-date"><i class="far fa-user"></i>addmin</span>
                            <span id="post-date"><i class="far fa-comments"></i>Featured</span>
                         </div>
                         <div id="blogpost-box">
                             <p id="blogpost-title">{{ object.blog_title }}</p>
                              <p id="blogpost-des">{{ object.blog_details }}</p>
                              
                         </div>
                     </div><!-- blog post -->
                  </div>
                  {% endfor %}
                  <div class="col-sm-3" id="cata-box-part">
                     <p id="footer-row-title" class="link-title">LINKS</p>
                     <ul id="cata-list">
                        <li><span id="blog-cata-list">CATEGORIES</span></li>
                        <li><hr id="blog-cata-line"></li>
                        <li><i class="fa fa-chevron-right"></i><span>Painting</span></li>
                        <li><i class="fa fa-chevron-right"></i><span>Business </span></li>
                        <li><i class="fa fa-chevron-right"></i><span> Website Design </span></li>
                        <li><i class="fa fa-chevron-right"></i><span> Music </span></li>
                        <li><i class="fa fa-chevron-right"></i><span> Photography </span></li>
                        <li><i class="fa fa-chevron-right"></i><span> Sport </span></li>
                     </ul>
                  </div>
               </div>
            </div>
         </div>
       </section><!--       /Blog section    -->    

{% endblock %}

index/templates/index/about-us.html
{% load static %}

<section id="my-stroy-section">
  <div class="container">
     <div class="row">
        <div class="col-sm-4">
            <img src="{% static 'img/story-img.jpg' %}" id="stroy-img">
        </div>
        <div class="col-sm-8" id="stroy-text-box">
            <p id="stroy-title">THE STORY ABOUT US</p>
            
              <hr class="red-line">
            <div>
            <p id="stroy-subtitle">We are driven by creating experiences that deliver results for your business and for your consumers. Our approach is simple and iterative.</p>
            </div>  
            <p id="stroy-description">The point of using Lorem Ipsum is that it has amore or less normal distribution of letters as opposed to using making it look like anes readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text and a search for there many web sites have 
            over the years.</p>
            <div class="col-sm-4 col-xs-4 story">
               <i class="fa fa-mobile"></i>
               <p id="icon-text"> 01. Retina Ready</p>
            </div>
            <div class="col-sm-4 col-xs-4 story">
              <i class="fa fa-wrench"></i> 
              <p id="icon-text"> 02. Easy to Customize</p>
            </div>
            <div class="col-sm-4 col-xs-4 story">
              <i class="fas fa-pencil-alt"></i>
              <p id="icon-text"> 03. Unique design</p>
            </div>
        </div>
     </div>
  </div> 
</section><!--           /My stroy        -->

index/templates/index/about.html
{% extends 'index/base.html' %}
{% load static %}


{% block content %}

	<section id="about-section">
      <div id="about-text-box">
        <p id='about-page-title'>About</p>
   	    <span id='home-page-link'><a href="#">Home</a></span><span>/</span><span id='about-page-link'><a>About</a></spna>
   	  </div>  
   </section><!--       /About    -->


   {% include 'index/about-us.html' %}


   <section id="build-with-us">
	      <div class="container">
	         <div class="row">
	             <div id="our-services-text-box">
	                <p id='our-services-small-title'>BEST SERVIECE</p>
	                <p id='our-services-big-title'>OUR WORK FLOW</p>
	                <hr id="our-services-line"/>
	             </div>

                <div class="col-sm-12" id="about-us-part">
		             <div class="col-sm-3">
		                <i class="fas fa-lightbulb" id="about-page-icon-list"></i>
		                <div id="best-service-list">
		                  <p id="about-us-icon-title">PLANNING</p>
		                  <p id="about-us-icon-x">X</p>
		                  <p id="about-us-icon-des">Cras mattis consectetur purus sites samet it fermentum.</p>
		                </div>
		             </div>
		             <div class="col-sm-3">
		                <i class="fas fa-pen-nib" id="about-page-icon-list"></i>
		                <div id="best-service-list">
		                  <p id="about-us-icon-title">DESIGN</p>
		                  <p id="about-us-icon-x">X</p>
		                  <p id="about-us-icon-des">Cras mattis consectetur purus sites samet it fermentum.</p>
		                </div>
		             </div>
		             <div class="col-sm-3">
		                <i class="fas fa-bezier-curve" id="about-page-icon-list"></i>
		                <div id="best-service-list">
		                  <p id="about-us-icon-title">DEVELOPING</p>
		                  <p id="about-us-icon-x">X</p>
		                  <p id="about-us-icon-des">Cras mattis consectetur purus sites samet it fermentum.</p>
		                </div>
		             </div>
		             <div class="col-sm-3">
		                <i class="fas fa-desktop" id="about-page-icon-list"></i>
		                <div id="best-service-list">
		                  <p id="about-us-icon-title">PRESENTATION</p>
		                  <p id="about-us-icon-x">X</p>
		                  <p id="about-us-icon-des">Cras mattis consectetur purus sites samet it fermentum.</p>
		                </div>
		             </div>
		        </div>     
	             

	             

	         </div>
	      </div>
        </section><!--           /Build with us      -->



        {% include 'index/client.html' %}


{% endblock %}

index/templates/index/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="no-js">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge"> 
		<meta name="viewport" content="width=device-width, initial-scale=1"> 
		<title>Arman academy</title>
    <link rel="icon" href="{% static 'img/logo-small.png' %}" />
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
		<link href='http://fonts.googleapis.com/css?family=Raleway:200,400,600' rel='stylesheet' type='text/css'>
		<link href="https://fonts.googleapis.com/css?family=Palanquin+Dark" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=PT+Serif" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'css/normalize.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'css/demo.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'css/component.css' %}" />
    <link rel="stylesheet" href="{% static 'css/baguetteBox.css' %}">
    <link rel="stylesheet" href="{% static 'css/home-gallery.css' %}">

	</head>
	<body>
       
    <section id="menu">
     <div class="container">
    	   <div class="row">
           <div class="col-sm-12">
              <div class="col-sm-3">
                  <a href="{% url 'index:home' %}"><img src="{% static 'img/logo.png' %}" id="main-logo"></a>
              </div>
              <div class="col-sm-7">
                  <ul id="main-menu-bar">
                     <li><a href="{% url 'index:home' %}">HOME</a></li>
                     <li><a href="{% url 'index:about' %}">ABOUT</a></li>
                     <li><a href="{% url 'services:services' %}">Services</a></li>
                     <li><a href="{% url 'portfolio:portfolio' %}"> PORTFOLIO </a></li>
                     <li><a href="{% url 'pages:pages' %}">Pages</a></li>
                     <li><a href="{% url 'blog:blog' %}">BLOG</a></li>
                     <li><a href="#">CONTACT</a></li>
                  </ul>
              </div>
              <div class="col-sm-2">
                  <ul id="logo-menu-bar">
                     <li><a><i class="fab fa-behance"></i></a></li>
                     <li><a><i class="fab fa-facebook-f"></i></a></li>
                     <li><a><i class="fab fa-twitter"></i></a></li>
                     <li><a><i class="fab fa-dribbble"></i></a></li>
                  </ul>
              </div>
           </div>
    	   </div>
    	 </div> 
    </section><!--       /Main menu    -->

    <section id="mobile-menu-bar">

    	    <div id="mobile-menu-part">
              <a href="#"><img src="{% static 'img/logo.png' %} id="main-logo"></a>
             <button id="side-menu" class="side-menu">
                  <i class="fa fa-bars side-menu-bar"></i>
              </button>
    	    </div>
    	    
        <ul id="mobile-menu">
            <a href="{% url 'index:home' %}"><li><p>HOME<p></li></a>
            <a href="{% url 'index:about' %}"><li><p>ABOUT</p></li></a>
            <a href="{% url 'services:services' %}"><li><p>SERVICES</p></li></a>
            <a href="{% url 'portfolio:portfolio' %}"><li><p>PORTFOLIO</p></li></a>
            <a href="{% url 'pages:pages' %}"><li><p>PAGES</p></li></a>
            <a href="{% url 'blog:blog' %}"><li><p>BLOG</p></li></a>
            <a href="#"><li><p>CONTACT</p></li></a>
        </ul>
    </section><!--       /Mobile menu    -->


    {% block content %}

    {% endblock %}


    <section>
       <div class="container-fluid">
         <div class="row">
            <div class="col-sm-2 col-xs-6 img-row-list">
                <img src="{% static 'img/photo-1.jpg' %}">
            </div>
            <div class="col-sm-2 col-xs-6 img-row-list">
                <img src="{% static 'img/photo-2.jpg' %}">
            </div>
            <div class="col-sm-2 col-xs-6 img-row-list">
                <img src="{% static 'img/photo-3.jpg' %}">
            </div>
            <div class="col-sm-2 col-xs-6 img-row-list">
                <img src="{% static 'img/photo-4.jpg' %}">
            </div>
            <div class="col-sm-2 col-xs-6 img-row-list">
                <img src="{% static 'img/photo-5.jpg' %}">
            </div>
            <div class="col-sm-2 col-xs-6 img-row-list">
                <img src="{% static 'img/photo-6.jpg' %}">
            </div>
          </div>  
        </div>  
      </section> --><!--           /gallery-row  --> 



    <section id="footer-section">
      <div class="container">
           <div class="row">
              <div class="col-sm-3" id="footer-box-part">
                 <p id="footer-row-title">ABOUT US</p>
                 <p id="footer-row-des">At vero eos et accusamus et iusto stagnismos ducimus os quidtiiss praetium ptatu mole deeniti .</p>
                 <div id="footer-text-box">
                   <i class="fa fa-map"></i>
                   <span>10th Floor,Washington Square Park, NY, United States.</span>
                 </div>
                  <div id="footer-text-box">
                   <i class="fa fa-envelope"></i>
                   <span>Support@domain.com</span>
                 </div>
                  <div id="footer-text-box">
                   <i class="fa fa-phone"></i>
                   <span>(004)+ 124 45 78 678</span>
                 </div>
              </div>
              <div class="col-sm-3" id="footer-box-part">
                 <p id="footer-row-title" class="link-title">LINKS</p>
                 <ul id="footer-list">
                    <li><i class="fa fa-chevron-right"></i><span>Home</span></li>
                    <li><i class="fa fa-chevron-right"></i><span>About us</span></li>
                    <li><i class="fa fa-chevron-right"></i><span>Services</span></li>
                    <li><i class="fa fa-chevron-right"></i><span>Features</span></li>
                    <li><i class="fa fa-chevron-right"></i><span>Portfolio</span></li>
                    <li><i class="fa fa-chevron-right"></i><span>Blog</span></li>
                    <li><i class="fa fa-chevron-right"></i><span>Contact</span></li>
                 </ul>
              </div>
              <div class="col-sm-3" id="footer-box-part">
                 <p id="footer-row-title">Social Media</p>
                 <ul id="footer-social-list">
                    <li><a><i class="fab fa-behance"></i></a></li>
                    <li><a><i class="fab fa-facebook-f"></i></a></li>
                    <li><a><i class="fab fa-twitter"></i></a></li>
                    <li><a><i class="fab fa-dribbble"></i></a></li>
                 </ul>
              </div>
              <div class="col-sm-3" id="footer-box-part">
                 <p id="footer-row-title">NEWSLETTER</p>
                 <p id="footer-row-des">Subscribe Our Newsletter get the Important News. The Amazing Offers & Inside Scoops:</p>
                 <input type="" name="" placeholder="Email Address" id="footer-input"><a id="footer-button"><i class="fas fa-search"></i></a>
              </div>
           </div>
      </div>
    </section><!--           /footer     -->


	  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
		<script src="{% static 'js/modernizr.custom.js' %}"></script>
		<script src="{% static 'js/classie.js' %}"></script>
		<script src="{% static 'js/boxesFx.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/baguetteBox.js' %}"></script>
    <script>
    baguetteBox.run('.tz-gallery');
    </script>
		<script>
			new BoxesFx( document.getElementById( 'boxgallery' ) );
		</script>
	</body>
</html>

index/templates/index/client.html
{% load static %}

<section id="our-client">
  <div class="container">
     <div class="row">
         <div id="our-services-text-box">
            <p id='our-client-small-title'>OUR CLIENTS</p>
            <p id='our-client-big-title'>CLIENTS WORK WITH US</p>
            <hr id="our-client-line"/>
            <p id="our-client-disc">“A shadowy flight into the dangerous world of a man who does not exist. We're gonna do it. On your mark get set . Got a dream and we just know now we're gonna make our dream come true! Why do we always come here guess well never know. Its like a kind of torture to have to watch the show.”</p>
         </div>

         <div class="col-sm-3" id="client-img">
             <img src="{% static 'img/c-img-1-1.png' %}">
         </div>
         <div class="col-sm-3" id="client-img">
             <img src="{% static 'img/c-img-1-2.png' %}">
         </div>
         <div class="col-sm-3" id="client-img">
             <img src="{% static 'img/c-img-1-3.png' %}">
         </div>
         <div class="col-sm-3" id="client-img">
             <img src="{% static 'img/c-img-1-2.png' %}">
         </div>
         

     </div>
  </div>
</section>          <!--   /our-client    -->

index/templates/index/home.html
{% extends "index/base.html" %}
{% load static %}
	
	{% block content %}

	   <div class="container">

	   	{% if slider %}
  			<!-- Top Navigation -->
  			<div id="boxgallery" class="boxgallery" data-effect="effect-1">
  				{% for object in slider %}
  				<div class="panel"><img src="{{ object.slider_img.url }}" alt="Image 1"/></div>
  				{% endfor %}
  			</div>

  		{% else %}

  			<div id="boxgallery" class="boxgallery" data-effect="effect-1">
  				<div class="panel"><img src="{% static 'img/benches.jpg' %}" alt="Image 1"/></div>
  			</div>

  		{% endif %}
  			<header class="codrops-header">
  				<h1> dream big act </h1>
  				<h1 id='second-title'> small begin now  </h1>
  				<span>follow your dreams and reach for the stars</span>
  				<div id="button-group">
  					<a id="learn-more-button">Learn More</a>
  					<a id="buy-more-button">Buy it now</a>
  			    </div>		
  			</header>
		  </div><!--       /Main Slider   -->

		  {% include 'index/about-us.html' %}
  
		  {% include 'index/our-service.html' %}

	    <section id="img-gallery">
	      <div class="container" id="gallery-container">
	         <div class="row">
	             <div id="our-services-text-box">
	                <p id='our-services-small-title'>OUR AMAZING WORKS</p>
	                <p id='our-services-big-title'>LET US BLOW YOUR MIND</p>
	                <hr id="our-services-line"/>
	                <p id="our-services-disc">We are driven by creating experiences that deliver results for your business and for your consumers. Our approach is simple and iterative.Sed ut perspiciatis unde omnis.</p>
	             </div>

	             <div class="tz-gallery">
	             	{% for object in gallery %}
	                <div class="col-xs-6 col-md-4" id="home-gallery-img-box">
	                <a class="lightbox" href="{{ object.gallery.url }}">
	                    <img src="{{ object.gallery.url }}" alt="Bridge">
	                </a>
		            </div>
		            {% endfor %}
	             </div>  --><!-- gallery-img-inside -->
	          </div>
	       </div>
	    </section> --><!--           /our-gallery-imag      -->

	    <section id="more-gallery-image">
	     <div class="container">
	      <div class="row">
	         <div class="col-sm-6 col-xs-8">
	           <div class="col-sm-1 col-xs-2">
	            <i class="fa fa-pencil" "=""></i>
	           </div>
	           <div class="col-sm-10 col-xs-10">
	             <p id="more-gallery-title">WANT TO SEE MORE AMAZING WORKS?</p>
	           </div>   
	         </div>
	         <div class="col-sm-6 col-xs-4" id="view-more-box">
	            <a href="portfolio.html"><span id="view-more-text">View More</span><span id="more-icon">+</span></a>
	         </div>
	      </div>
	     </div> 
	    </section>      <!--     /our-gallery-imag      -->

	    <section id="our-team">
	      <div class="container">
	         <div class="row">
	             <div id="our-services-text-box">
	                <p id='our-services-small-title'>WE PUT OUR PEOPLE FIRST</p>
	                <p id='our-services-big-title'>MEET OUR CREATIVE TEAM</p>
	                <hr id="our-services-line"/>
	                <p id="our-services-disc">We are driven by creating experiences that deliver results for your business and for your consumers. Our approach is simple and iterative.Sed ut perspiciatis unde omnis.</p>
	             </div>

	             {% for object in employe %}
	             <div class="col-xs-12 col-sm-4 our_team_number_box1" >
	                 <div id="our_team_number_des1">
	                     <p id="our_team_number_name">{{ object.emp_name }}</p>
	                     <p id="our_team_number_position">{{ object.emp_position }}</p>
	                 </div>
	                 <img src="{{ object.emp_photo.url }}" id="our_team_number_image">
	             </div>
	             {% endfor %}
	         </div>
	      </div>
	    </section> --><!--           /our-team     -->

	    {% include 'index/ourfeaters.html' %}

	    <section id="build-brand-section">
	      <div class="container">
	         <div class="row">
	            <div class="col-sm-6" id="build-bran-text-box">
	               <p id="stroy-title">Building Brands on the Website</p>
	                
	                  <hr class="red-line">
	                <div>
	                <p id="build-brand-sub">High Resolution Graphics</p>
	                </div>  
	                <p id="build-brand-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ante ex fermentum vel libero eget interdum semper libero. Curabitur egestas velit velitarcu id tempor convallis.Cras dignissim, diam vitae ornare molestiete ligula magna imperdiet velit volutpat tortor.</p>
	                <p id="build-brand-button">purchase now</p>
	            </div>
	            <div class="col-sm-6">
	               <img src="{% static 'img/i-bundle.jpg' %}" id="build-brand-img" class="img-responsive">
	            </div>
	         </div>
	      </div>
	    </section>

		{% include 'index/client.html' %}    

    {% endblock %}

index/templates/index/our-service.html
{% load static %}

<section id="our-services">
  <div class="container">
     <div class="row">
         <div id="our-services-text-box">
            <p id='our-services-small-title'>OUR SERVICES</p>
            <p id='our-services-big-title'>SERVICES WHAT WE OFFERS</p>
            <hr id="our-services-line"/>
            <p id="our-services-disc">We are driven by creating experiences that deliver results for your business and for your consumers. Our approach is simple and iterative.Sed ut perspiciatis unde omnis.</p>
         </div>

         {% if services %}

            {% for object in services %}
               <div class="col-sm-4 col-xs-12 our-services-icons">
                  <div class="col-sm-2 col-xs-2">
                     <i class="fa fa-mobile"></i>
                  </div>
                  <div class="col-sm-10 col-xs-10">
                    <p id="our-services-icons-title">{{ object.service_title }}</p>
                     <hr id="our-services-icons-line">
                     <p id="our-services-icons-desc">{{ object.service_detail }}</p>
                  </div>
               </div>
            {% endfor %}

          {% else %}
              <div id="our-services-text-box">
                  
                  <p id='our-services-big-title'>THERE IS NO SERVICE</p>
              </div>
          {% endif %}
     </div>
  </div>
</section> --><!--           /our-services     --> 